### ISSUE TITLE
Example website throws error: ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by weidenhaus** [microsoft/TypeScript-Node-Starter#266] opened 2020-01-23 20:50 UTC
Website can't be reached: http://typescript-node-starter.azurewebsites.net
ERR_NAME_NOT_RESOLVED

**Comment by orta** [comment] 2020-01-24 15:51
Dupe of https://github.com/microsoft/TypeScript-Node-Starter/issues/258

**Closed by orta** 2020-01-24 15:51 UTC
