### ISSUE TITLE
The README.md live demo link is broken

### ISSUE THREAD

**Issue by tjcchen** [microsoft/TypeScript-Node-Starter#343] opened 2021-09-01 00:58 UTC
Hi there,

I just found this link pasted on readme.md is not working, please help update, thx!

https://typescript-node-starter.azurewebsites.net/

**Comment by gaborszita** [comment] 2021-09-12 19:10
Duplicate of:
#258 
#243

**Comment by orta** [comment] 2021-09-14 14:44
closing as dupe

**Closed by orta** 2021-09-14 14:44 UTC
Labels: duplicate

**Comment by tjcchen** [comment] 2021-09-17 00:56
thanks a lot!
